In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
xtrain = np.array([[1,1,1],
                   [1,0,1],
                   [1,0,0],
                   [1,0,0],
                   [1,1,1],
                   [0,1,1],
                   [0,0,0],
                   [1,0,1],
                   [0,1,0],
                   [1,0,0]])
ytrain = np.array([1,1,0,0,1,0,0,1,1,0])

In [4]:
print(xtrain[0:10])

[[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]]


In [5]:
print(ytrain)

[1 1 0 0 1 0 0 1 1 0]


In [7]:
print("Shape XTrain -", xtrain.shape)
print("Shape YTrain -", ytrain.shape)
print("M -", len(xtrain))

Shape XTrain - (10, 3)
Shape YTrain - (10,)
M - 10


In [8]:
def entropy_function(y) :
    entropy = 0
    if len(y) != 0:
        p1 = len(y[y==1])/len(y)

        if p1 != 1 and p1 != 0 :
            entropy = (-p1)*(np.log2(p1)) - (1-p1)(np.log2(1-p1))
            
    return entropy

In [ ]:
def data_split(X, node_index, feature)